name: r-httpcache

on:
  push:
    paths:
      - '.github/workflows/r-httpcache.yml'
      - 'pkginstall.sh'
      - 'r-httpcache/**'
      # Dependencies


jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2

      - name: Install r-httpcache
        working-directory: r-httpcache
        run: |
          ../pkginstall.sh user=alex pkg=r-httpcache
