name: r-tau

on:
  push:
    paths:
      - '.github/workflows/r-tau.yml'
      - 'pkginstall.sh'
      - 'r-tau/**'
      # Dependencies


jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2

      - name: Install r-tau
        working-directory: r-tau
        run: |
          ../pkginstall.sh user=alex pkg=r-tau
