name: r-tree

on:
  push:
    paths:
      - '.github/workflows/r-tree.yml'
      - 'pkginstall.sh'
      - 'r-tree/**'
      # Dependencies


jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2

      - name: Install r-tree
        working-directory: r-tree
        run: |
          ../pkginstall.sh user=alex pkg=r-tree
