name: r-vader

on:
  push:
    paths:
      - '.github/workflows/r-vader.yml'
      - 'pkginstall.sh'
      - 'r-vader/**'
      # Dependencies


jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2

      - name: Install r-vader
        working-directory: r-vader
        run: |
          ../pkginstall.sh user=alex pkg=r-vader
